### PR TITLE
Add skewX/Y methods to API

### PR DESCRIPTION
**Pull request by jamesots**
SVG defines six transformations: translate, rotate, scale, matrix, skewX and skewY. I thought it would be sensible and useful to have all of these in the API.

### CODE REVIEW

**Comment by puzrin** [comment]
This module is old/mature and nobody still said that it lacks of SkewX/Y. I prefer to keep APIs clear & simple and avoid adding everything possible without practical reasons. Do you have ones?

Those rare operations are still available via `.matrix()` / `.transform()`, and i don't know why it worth to pin those at top level.

**Comment by jamesots** [comment]
I was writing some code and tried to call skewX, assuming it would be in the API as it's an SVG transformation, but it wasn't there. I initially copied the code out of the Matrix class, but then thought it would be better not to duplicate code but to make the API complete instead, and have all six SVG transformations available.

If you think this is a bad idea for some reason, I can just use my fork, I guess.

**Comment by puzrin** [comment]
Ok, let's accept it, but please add tests first (copy from [transform](https://github.com/fontello/svgpath/blob/master/test/transform.js#L54)) & squash to single commit.

**Comment by puzrin** [comment]
Added by https://github.com/fontello/svgpath/commit/44f5c8e96d98b78eeb11691609220dbff662d4c1.

I can release it, if you don't plan to PR anything else (typescript definition?).

**Pull request closed without merging**
