### PR TITLE
Fix arc transform bug

### PR DESCRIPTION
**Pull request by kpym**
I came to rewrite the arc transform.
The idea is that any ellipse is a transform of the unit circle. 
So any transform of an ellipse can be precomposed by another transform and considered as transform of the unit circle.
To find the image of a unit circle by a transform M, we need to find the eigenvalues and the eigenvectors ot M*transpose(M).
Actually to encode in svg an elliptic arc we need only the angle of the first eigenvector.

### CODE REVIEW

**Comment by puzrin** [comment]
Looks working, but:

- not sure about matrix.copy, probably via constructor: `new Matrix(m)`. Need to think about.
- chainable matrix ops looks expensive in this case (that's done for each arc segment, and rotate adds 3 matrixes).
- no tests
- edge conditions (radii correction, negative rx/ry) not covered
- seems to be better in separate file `arc_transform` (too many complex math in switch).

I've written reference links in issue. If you wish, i'll ask @rlidwka to solve issue in a couple of days.

**Comment by puzrin** [comment]
copy = (new Matrix()).matrix(m.toArray) - no changes needed

**Comment by kpym** [comment]
> copy = (new Matrix()).matrix(m.toArray) - no changes needed
is not exactly the same (one copy all matrices, the other copy the result), but in some sens I can't understand your matrix object.
Your matrix object is a sequence of matrices, but you never use it like this. 
For example your __stack is an array ot matrix objects. 
Why it is not just a matrix object (which is already an array of matrices) ?

**Comment by kpym** [comment]
> chainable matrix ops looks expensive in this case (that's done for each arc segment, and rotate adds 3 matrixes).

If you find a faster solution (that works) it will be nice. But I don't think that you can cut the time by two here. Finding the image of a conic is never "trivial". 

> no tests

If there was no test before, there is not now ;) 

> edge conditions (radii correction, negative rx/ry) not covered

what do you mean ? negative rx/ry must work well (I suppose never checked) because the signe is irrelevant here. 

> seems to be better in separate file arc_transform (too many complex math in switch).

I agree.

**Comment by puzrin** [comment]
> For example your __stack is an array ot matrix objects.
> Why it is not just a matrix object (which is already an array of matrices) ?

`__stack` is for "operations", not for matrixes only. For example, maybe sometime it will optimize `.abs().rel().abs().rel()`. Also, earlier scale & translate had different implementation without matrixes.

> what do you mean ? negative rx/ry must work well (I suppose never checked) because the signe is irrelevant here.

See http://www.w3.org/TR/SVG/implnote.html#ArcCorrectionOutOfRangeRadii . SVGO implements it. That's more formatting issue than math, but since we completely drop defective algorithm, it worth to solve all related things.

**Comment by kpym** [comment]
> `__stack` is for "operations", not for matrixes only. For example, maybe sometime it will optimize `.abs().rel().abs().rel()`. Also, earlier scale & translate had different implementation without matrixes.

The initial idea was "theoretically" good. Keeping all this opérations to optimise them at some point is interesting (for example if you have successif scales you can combine them before to apply them)... but now it is completely un-optimized:
* You have this matrix object that is array of matrices and every time you add a new one you add it "on the right" (because of how `toArray` works). This complex object is never used ! You only use matrices with array of only one matrix.
* Your `__stack` is _de facto_ the same as your matrix object but where transforms are added "on the left" (this is how `__evaluateStack`) works. It was probably initially designed to contain "operations", but now it contains only matrix transforms. 
* Your `__stack` is created for optimisation, but there are no optimisations, only lost of performance because every time you add a new transformation in your stack the cache is emptied and all matrix multiplications are lost. I understand that this is the idea if we want to make some optimisations to improve the accuracy, but this is not the case for the moment.

I think that all this should be "flattened" ! You don't need the matrix object, only the `combine` function. You can replace your `__stack` by `transform` (that is initially identity) and every time you add a transformation `newone` you just do `transform=combine(newone,transform)`.

**Comment by kpym** [comment]
> See http://www.w3.org/TR/SVG/implnote.html#ArcCorrectionOutOfRangeRadii . SVGO implements it. That's more formatting issue than math, but since we completely drop defective algorithm, it worth to solve all related things.

Replacing arc by a line if `rx==0` or `ry==0` should be done (and `==0` should be replaced by `< epsilon` du to precision errors). I'll put all this in a separate file `ellipse_transform.js` and make a new pull request.

**Comment by puzrin** [comment]
See https://github.com/fontello/svgpath/blob/master/lib/a2c.js#L112-L145 it does the similar things but in different way. Need to think how to unify math (normalize + convert to circular).

> Your __stack is created for optimisation, but there are no optimisations, only lost of performance because every time you add a new transformation in your stack the cache is emptied and all matrix multiplications are lost.

That's not correct. Current code is not compleete, but there are no perf loss. It's left as is for several reasons:

- Stack & maths were written independently in different time slices.
- Change stack to matrix array will change extentibility to impossible due close-coupled code. In long term it's better when logic is splitted to isolated blocks instead of big one.
- Premature & micro optimizations are evil.

**Comment by kpym** [comment]
> That's not correct. Current code is not compleete, but there are no perf loss.

I came to check and you dont have perfs lost because when you do `__evaluateStack` you not simply evaluate the stack but you also apply it ! So if after `__evaluateStack` you do some "inverse" transforms the errors will accumulate :(

But you have potential perfs lost in `matrix` because every time you add new transform you empty the cach. But you dont use this anyway ;)

> Stack & maths were written independently in different time slices.

That's why I said to "flatten" all now ;)

> Change stack to matrix array will change extentibility to impossible due close-coupled code. In long term it's better when logic is splitted to isolated blocks instead of big one.

This is not what you are doing now. And I don't know what ideas you have, but I'm working now on an extension of this project to add `.toBondingBoxString` (to calculate the bounding box of a path) and `.inBox("0 0 100 100 meet xMinYmax")` (=scale and translate to put in a box) and before to apply `inBox` I need to calculate the bounding box. And so to apply the previous transforms before to add new ones... To do this I copy the path, evaluate the transforms, get the boundnig box and finally apply the new transform to the original path. I can't see how I can use your complex __stack/matrix to "extend" it. 

> Premature & micro optimizations are evil.

I'm not talking only about speed optimisation (personally I don't need it). I'm talking to make the code more consistant with what it is doing.
Create a complex code without a precise idea of how we will use this complexity one day is not good.
If you have in mind some particular application that will use the complexity of `matrix` AND of `__stack`, then it is obviously justified. Else, IMO, not.

**Comment by puzrin** [comment]
> If you have in mind some particular application that will use the complexity of matrix AND of __stack, then it is obviously justified. Else, IMO, not.

I understand your arguments. Current situation is, that i don't know if ops reorder optimization will be done, but it's a bit early to reject those. So, i prefer to keep this parts unchanged. Those looks strange, but not horrible. You can call [this.__evaluateStack()](https://github.com/fontello/svgpath/blob/master/lib/svgpath.js#L185) anytime to flush pending ops, before applying something "uncommutable".

PS. For bounding box take a look at https://github.com/icons8/svg-path-bounding-box. I wished to implement something similar in svgpath, but did not found time and motivation to finish :).

**Comment by puzrin** [comment]
I remendered, abs() & rel() operations do not touch pending ops https://github.com/fontello/svgpath/blob/master/lib/svgpath.js#L460.

I don't know why i did those, probably, just for lulz :)

**Comment by kpym** [comment]
> For bounding box take a look at https://github.com/icons8/svg-path-bounding-box. I wished to implement something similar in svgpath, but did not found time and motivation to finish :).

I have created my own method that works fine. I'll have to check if this one is better ...

**Pull request closed without merging**
