### PR TITLE
add skipStringOptimizations options to toString

### PR DESCRIPTION
**Pull request by Klaasvaak**
I'm optimizing the performance of a project I'm working on. It contains large paths (for example with a length of 160k). When skipping the string optimizations in toString I can see performance improvements around 7-11x. When having multiple of these large paths this adds up.

I made a simple example here: https://codepen.io/klaasvaak/pen/dyVjPje?editors=1011

Let me know if you have concerns about skipping these string optimizations.

### CODE REVIEW

**Comment by puzrin** [comment]
Are you sure this option required for other users? For example, you could just override prototype method (or do it in inherited class)

**Comment by Klaasvaak** [comment]
@puzrin Very good point. I will do this instead.

**Comment by puzrin** [comment]
No problem, happy to help.

BTW

- It's better to use `benchmark.js`, because single pass may be not enough to "warm up" JIT inline caches. See https://github.com/fontello/svgpath/tree/master/benchmark.
- You could try to optimize existing `.toString()` instead. For example:
  - use `String.test(regexp)` before `String.replace(regexp)`.
  - use more clever join, instead of join everything via space and then removing those back https://github.com/fontello/svgpath/blob/70134e408751daf035f0e84b1a5628c1cdf4b995/lib/svgpath.js#L201-L207. Existing code is from old time, when i tried to make all steps atomic, because was not certain about desired final sequence.

I did not experimented with this part of code too much. But after your example, i think there is room for improvements.

FYI. If you plan to dive into perfomance area, i strongly recommend to read this blog https://mrale.ph/. Because v8 JIT logic is completely different than anything "possible to imagine by normal human" :).

**Comment by Klaasvaak** [comment]
@puzrin Thank you for sharing of this, this is very useful for me.

**Comment by puzrin** [comment]
See v2.5.0.

```sh
./benchmark/benchmark.js 
.from("big.txt")

  > 2.4.1 x 10.33 ops/sec ±2.97% (30 runs sampled)
  > current x 10.33 ops/sec ±3.71% (30 runs sampled)

.from("one_path.txt")

  > 2.4.1 x 7,588 ops/sec ±2.90% (92 runs sampled)
  > current x 7,719 ops/sec ±1.42% (94 runs sampled)

.from(long).toString()

  > 2.4.1 x 3.17 ops/sec ±1.60% (12 runs sampled)
  > current x 103 ops/sec ±0.91% (74 runs sampled) <============
```

Enjoy!

**Comment by Klaasvaak** [comment]
@puzrin This is great, thanks! I can confirm using the newest version `.toString()` in my project speeds things up as well :)

**Pull request closed without merging**
